/**
 * Currency codes Channex accepts for properties (ISO 4217 subset).
 * Source: GET https://staging.channex.io/api/v1/currencies
 * Snapshot — refresh if Channex adds/removes codes.
 */
export type ChannexCurrency = { code: string; label: string }

export const CHANNEX_CURRENCIES: readonly ChannexCurrency[] = [
  { code: 'AED', label: 'UAE Dirham (AED)' },
  { code: 'AFN', label: 'Afghani (AFN)' },
  { code: 'ALL', label: 'Lek (ALL)' },
  { code: 'AMD', label: 'Armenian Dram (AMD)' },
  { code: 'AOA', label: 'Kwanza (AOA)' },
  { code: 'ARS', label: 'Argentine Peso (ARS)' },
  { code: 'AUD', label: 'Australian Dollar (AUD)' },
  { code: 'AWG', label: 'Aruban Guilder (AWG)' },
  { code: 'AZN', label: 'Azerbaijanian Manat (AZN)' },
  { code: 'BAM', label: 'Convertible Marks (BAM)' },
  { code: 'BBD', label: 'Barbados Dollar (BBD)' },
  { code: 'BDT', label: 'Taka (BDT)' },
  { code: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { code: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { code: 'BIF', label: 'Burundi Franc (BIF)' },
  { code: 'BMD', label: 'Bermudian Dollar (customarily known as Bermuda Dollar) (BMD)' },
  { code: 'BND', label: 'Brunei Dollar (BND)' },
  { code: 'BOB', label: 'Boliviano Mvdol (BOB)' },
  { code: 'BRL', label: 'Brazilian Real (BRL)' },
  { code: 'BSD', label: 'Bahamian Dollar (BSD)' },
  { code: 'BTN', label: 'Indian Rupee Ngultrum (BTN)' },
  { code: 'BWP', label: 'Pula (BWP)' },
  { code: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { code: 'BZD', label: 'Belize Dollar (BZD)' },
  { code: 'CAD', label: 'Canadian Dollar (CAD)' },
  { code: 'CDF', label: 'Congolese Franc (CDF)' },
  { code: 'CHF', label: 'Swiss Franc (CHF)' },
  { code: 'CLP', label: 'Chilean Peso Unidades de fomento (CLP)' },
  { code: 'CNY', label: 'Yuan Renminbi (CNY)' },
  { code: 'COP', label: 'Colombian Peso (COP)' },
  { code: 'CRC', label: 'Costa Rican Colon (CRC)' },
  { code: 'CUP', label: 'Cuban Peso Peso Convertible (CUP)' },
  { code: 'CVE', label: 'Cape Verde Escudo (CVE)' },
  { code: 'CZK', label: 'Czech Koruna (CZK)' },
  { code: 'DJF', label: 'Djibouti Franc (DJF)' },
  { code: 'DKK', label: 'Danish Krone (DKK)' },
  { code: 'DOP', label: 'Dominican Peso (DOP)' },
  { code: 'DZD', label: 'Algerian Dinar (DZD)' },
  { code: 'EGP', label: 'Egyptian Pound (EGP)' },
  { code: 'ERN', label: 'Nakfa (ERN)' },
  { code: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { code: 'EUR', label: 'Euro (EUR)' },
  { code: 'FJD', label: 'Fiji Dollar (FJD)' },
  { code: 'FKP', label: 'Falkland Islands Pound (FKP)' },
  { code: 'GBP', label: 'Pound Sterling (GBP)' },
  { code: 'GEL', label: 'Lari (GEL)' },
  { code: 'GHS', label: 'Cedi (GHS)' },
  { code: 'GIP', label: 'Gibraltar Pound (GIP)' },
  { code: 'GMD', label: 'Dalasi (GMD)' },
  { code: 'GNF', label: 'Guinea Franc (GNF)' },
  { code: 'GTQ', label: 'Quetzal (GTQ)' },
  { code: 'GYD', label: 'Guyana Dollar (GYD)' },
  { code: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { code: 'HNL', label: 'Lempira (HNL)' },
  { code: 'HTG', label: 'Gourde US Dollar (HTG)' },
  { code: 'HUF', label: 'Forint (HUF)' },
  { code: 'IDR', label: 'Rupiah (IDR)' },
  { code: 'ILS', label: 'New Israeli Sheqel (ILS)' },
  { code: 'INR', label: 'Indian Rupee (INR)' },
  { code: 'IQD', label: 'Iraqi Dinar (IQD)' },
  { code: 'IRR', label: 'Iranian Rial (IRR)' },
  { code: 'ISK', label: 'Iceland Krona (ISK)' },
  { code: 'JMD', label: 'Jamaican Dollar (JMD)' },
  { code: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { code: 'JPY', label: 'Yen (JPY)' },
  { code: 'KES', label: 'Kenyan Shilling (KES)' },
  { code: 'KGS', label: 'Som (KGS)' },
  { code: 'KHR', label: 'Riel (KHR)' },
  { code: 'KMF', label: 'Comoro Franc (KMF)' },
  { code: 'KPW', label: 'North Korean Won (KPW)' },
  { code: 'KRW', label: 'Won (KRW)' },
  { code: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { code: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
  { code: 'KZT', label: 'Tenge (KZT)' },
  { code: 'LAK', label: 'Kip (LAK)' },
  { code: 'LBP', label: 'Lebanese Pound (LBP)' },
  { code: 'LKR', label: 'Sri Lanka Rupee (LKR)' },
  { code: 'LRD', label: 'Liberian Dollar (LRD)' },
  { code: 'LSL', label: 'Rand Loti (LSL)' },
  { code: 'LYD', label: 'Libyan Dinar (LYD)' },
  { code: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { code: 'MDL', label: 'Moldovan Leu (MDL)' },
  { code: 'MGA', label: 'Malagasy Ariary (MGA)' },
  { code: 'MKD', label: 'Denar (MKD)' },
  { code: 'MMK', label: 'Kyat (MMK)' },
  { code: 'MNT', label: 'Tugrik (MNT)' },
  { code: 'MOP', label: 'Pataca (MOP)' },
  { code: 'MRU', label: 'Ouguiya (MRU)' },
  { code: 'MUR', label: 'Mauritius Rupee (MUR)' },
  { code: 'MVR', label: 'Rufiyaa (MVR)' },
  { code: 'MWK', label: 'Kwacha (MWK)' },
  { code: 'MXN', label: 'Mexican Peso (MXN)' },
  { code: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { code: 'MZN', label: 'Metical (MZN)' },
  { code: 'NAD', label: 'Rand Namibia Dollar (NAD)' },
  { code: 'NGN', label: 'Naira (NGN)' },
  { code: 'NIO', label: 'Cordoba Oro (NIO)' },
  { code: 'NOK', label: 'Norwegian Krone (NOK)' },
  { code: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { code: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { code: 'OMR', label: 'Rial Omani (OMR)' },
  { code: 'PAB', label: 'Balboa US Dollar (PAB)' },
  { code: 'PEN', label: 'Nuevo Sol (PEN)' },
  { code: 'PGK', label: 'Kina (PGK)' },
  { code: 'PHP', label: 'Philippine Peso (PHP)' },
  { code: 'PKR', label: 'Pakistan Rupee (PKR)' },
  { code: 'PLN', label: 'Zloty (PLN)' },
  { code: 'PYG', label: 'Guarani (PYG)' },
  { code: 'QAR', label: 'Qatari Rial (QAR)' },
  { code: 'RON', label: 'New Leu (RON)' },
  { code: 'RSD', label: 'Serbian Dinar (RSD)' },
  { code: 'RUB', label: 'Russian Ruble (RUB)' },
  { code: 'RWF', label: 'Rwanda Franc (RWF)' },
  { code: 'SAR', label: 'Saudi Riyal (SAR)' },
  { code: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
  { code: 'SCR', label: 'Seychelles Rupee (SCR)' },
  { code: 'SDG', label: 'Sudanese Pound (SDG)' },
  { code: 'SEK', label: 'Swedish Krona (SEK)' },
  { code: 'SGD', label: 'Singapore Dollar (SGD)' },
  { code: 'SHP', label: 'Saint Helena Pound (SHP)' },
  { code: 'SLE', label: 'Leone (SLE)' },
  { code: 'SOS', label: 'Somali Shilling (SOS)' },
  { code: 'SRD', label: 'Surinam Dollar (SRD)' },
  { code: 'SSP', label: 'South Sudanese Pound (SSP)' },
  { code: 'STN', label: 'Dobra (STN)' },
  { code: 'SVC', label: 'El Salvador Colon US Dollar (SVC)' },
  { code: 'SYP', label: 'Syrian Pound (SYP)' },
  { code: 'SZL', label: 'Lilangeni (SZL)' },
  { code: 'THB', label: 'Baht (THB)' },
  { code: 'TJS', label: 'Somoni (TJS)' },
  { code: 'TMT', label: 'Manat (TMT)' },
  { code: 'TND', label: 'Tunisian Dinar (TND)' },
  { code: 'TOP', label: 'Pa\'anga (TOP)' },
  { code: 'TRY', label: 'Turkish Lira (TRY)' },
  { code: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)' },
  { code: 'TWD', label: 'New Taiwan Dollar (TWD)' },
  { code: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { code: 'UAH', label: 'Hryvnia (UAH)' },
  { code: 'UGX', label: 'Uganda Shilling (UGX)' },
  { code: 'USD', label: 'US Dollar (USD)' },
  { code: 'UYU', label: 'Peso Uruguayo Uruguay Peso en Unidades Indexadas (UYU)' },
  { code: 'UZS', label: 'Uzbekistan Sum (UZS)' },
  { code: 'VES', label: 'Venezuelan Bolivar Soberano (VES)' },
  { code: 'VND', label: 'Dong (VND)' },
  { code: 'VUV', label: 'Vatu (VUV)' },
  { code: 'WST', label: 'Tala (WST)' },
  { code: 'XAF', label: 'CFA Franc BEAC (XAF)' },
  { code: 'XCD', label: 'East Caribbean Dollar (XCD)' },
  { code: 'XOF', label: 'CFA Franc BCEAO (XOF)' },
  { code: 'XPF', label: 'CFP Franc (XPF)' },
  { code: 'YER', label: 'Yemeni Rial (YER)' },
  { code: 'ZAR', label: 'Rand (ZAR)' },
  { code: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
] as const

const CODES = new Set(CHANNEX_CURRENCIES.map((c) => c.code))

export function isChannexCurrency(code: string | null | undefined): boolean {
  return Boolean(code && CODES.has(code.trim().toUpperCase()))
}

